// ================================ Constantes =================================

// Mapeamento de códigos de idioma para locale padrão
export const LANG_TO_LOCALE: Record<string, string> = {
  pt: "pt-BR",
  en: "en-US",
  es: "es-ES",
};

// ================================ Traduções ================================

// Textos da aplicação em diferentes idiomas
export const I18N = {
  pt: {
    monthly: "Mensal",
    weekly: "Semanal",
    daily: "Diário",
    yearly: "Anual",
    app_title: "Contas a Pagar — v0.4",
    subtitle: "Sem presets. Armazena localmente. Exporte .ics para receber lembretes.",
    view_list: "Lista",
    view_calendar: "Calendário",
    filter_all: "Tudo",
    filter_today: "Hoje",
    filter_overdue: "Atrasadas",
    filter_next7: "+7d",
    filter_next30: "+30d",
    search_placeholder: "Buscar título/categoria/tags",
    totals_open: "Abertas",
    totals_month: "Mês",
    section_bills: "Contas",
    no_bills: "Nenhuma conta. Adicione a primeira com “+ Nova conta”.",
    due_on: "Vence em",
    paid_on: "Pago em",
    overdue: "Atrasada",
    pending: "Pendente",
    paid: "Pago",
    new_bill: "+ Nova conta",
    export_ics: "Exportar .ics (mês atual)",
    edit: "Editar",
    delete: "Excluir",
    mark_paid: "Marcar pago",
    pay_and_advance: "Pago e avançar",
    confirm_delete_title: "Excluir conta?",
    confirm_delete_body: "Esta ação não pode ser desfeita.",
    cancel: "Cancelar",
    confirm: "Confirmar",
    calendar_title: (label: string) => `Calendário — ${label}`,
    footer: "Feito para uso pessoal. v0.4 – armazenamento local.",
    settings: "Configurações",
    notifications: "Notificações",
    no_notifications: "Sem novas mensagens",
    appearance: "Aparência",
    theme: "Tema",
    light: "Claro",
    dark: "Escuro",
    system: "Sistema",
    language: "Idioma",
    general: "Geral",
    save: "Salvar",
    close: "Fechar",
  },
  en: {
    monthly: "Monthly",
    weekly: "Weekly",
    daily: "Daily",
    yearly: "Yearly",
    app_title: "Bills — v0.4",
    subtitle: "No presets. Local storage. Export .ics to get reminders.",
    view_list: "List",
    view_calendar: "Calendar",
    filter_all: "All",
    filter_today: "Today",
    filter_overdue: "Overdue",
    filter_next7: "+7d",
    filter_next30: "+30d",
    search_placeholder: "Search title/category/tags",
    totals_open: "Open",
    totals_month: "Month",
    section_bills: "Bills",
    no_bills: "No bills yet. Add the first with “+ New bill”.",
    due_on: "Due on",
    paid_on: "Paid on",
    overdue: "Overdue",
    pending: "Pending",
    paid: "Paid",
    new_bill: "+ New bill",
    export_ics: "Export .ics (current month)",
    edit: "Edit",
    delete: "Delete",
    mark_paid: "Mark paid",
    pay_and_advance: "Paid & advance",
    confirm_delete_title: "Delete bill?",
    confirm_delete_body: "This action cannot be undone.",
    cancel: "Cancel",
    confirm: "Confirm",
    calendar_title: (label: string) => `Calendar — ${label}`,
    footer: "Personal use. v0.4 – local storage.",
    settings: "Settings",
    notifications: "Notifications",
    no_notifications: "No new messages",
    appearance: "Appearance",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    language: "Language",
    general: "General",
    save: "Save",
    close: "Close",
  },
  es: {
  monthly: "Mensual",
  weekly: "Semanal",
  daily: "Diario",
  yearly: "Anual",
  app_title: "Cuentas por Pagar — v0.4",
  subtitle: "Sin presets. Almacenamiento local. Exporta .ics para recordatorios.",
  view_list: "Lista",
  view_calendar: "Calendario",
  filter_all: "Todo",
  filter_today: "Hoy",
  filter_overdue: "Atrasadas",
  filter_next7: "+7d",
  filter_next30: "+30d",
  search_placeholder: "Buscar título/categoría/etiquetas",
  totals_open: "Abiertas",
  totals_month: "Mes",
  section_bills: "Cuentas",
  no_bills: "Sin cuentas. Agrega la primera con “+ Nueva cuenta”.",
  due_on: "Vence el",
  paid_on: "Pagado el",
  overdue: "Vencida",
  pending: "Pendiente",
  paid: "Pagado",
  new_bill: "+ Nueva cuenta",
  export_ics: "Exportar .ics (mes actual)",
  edit: "Editar",
  delete: "Eliminar",
  mark_paid: "Marcar pagado",
  pay_and_advance: "Pagado y avanzar",
  confirm_delete_title: "¿Eliminar cuenta?",
  confirm_delete_body: "Esta acción no se puede deshacer.",
  cancel: "Cancelar",
  confirm: "Confirmar",
  calendar_title: (label: string) => `Calendario — ${label}`,
  footer: "Uso personal. v0.4 – almacenamiento local.",
  settings: "Configuraciones",
  notifications: "Notificaciones",
  no_notifications: "Sin nuevos mensajes",
  appearance: "Apariencia",
  theme: "Tema",
  light: "Claro",
  dark: "Oscuro",
  system: "Sistema",
  language: "Idioma",
  general: "General",
  save: "Guardar",
  close: "Cerrar",
  }
};

// ================================== Funções ==================================

// Hook para retornar traduções de acordo com o idioma selecionado
// Se o idioma não estiver definido, retorna português como padrão
export function useI18n(language: string) {
  return I18N[language as keyof typeof I18N] || I18N.pt;
}
